<!-- login.phtml -->
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="/assets/css/application.css">
</head>
<body>
    <div class="login-container">
        <header class="mb3">
            <h1><?= $title ?></h1>
        </header>
        <h3>Sistema de Matrículas</h3>
        <form action="/public/pages/login/login.php"  method="post">
            <label for="type">Tipo:</label>
            <select id="type" name="type" onchange="updateFormFields()">
                <option value="server">Servidor</option>
                <option value="student">Aluno</option>
            </select><br><br>

            <div id="dynamic-fields"></div>
            
            <label for="password">Senha:</label>
            <input type="password" id="password" name="password" class="password-field" required><br><br>
            
            <input type="submit" value="Login">
        </form>
    </div>

    <script>
        function updateFormFields() {
            const userType = document.getElementById('type').value;
            const dynamicFields = document.getElementById('dynamic-fields');
            dynamicFields.innerHTML = '';

            if (userType === 'student') {
                dynamicFields.innerHTML = `
                    <label for="email">Email:</label>
                    <input type="email" id="email" name="email" class="email-field" required><br><br>
                    <label for="ra">RA:</label>
                    <input type="text" id="ra" name="ra" class="ra-field" required><br><br>
                `;
            } else if (userType === 'server') {
                dynamicFields.innerHTML = `
                    <label for="email">Email:</label>
                    <input type="email" id="email" name="email" class="email-field" required><br><br>
                    <label for="id">ID:</label>
                    <input type="text" id="id" name="id" class="id-field" required><br><br>
                `;
            }
        }
    </script>
</body>
</html>
