<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página de Alunos</title>
    <link rel="stylesheet" href="/assets/css/alunos_professores.css">
</head>
<body>
    <div class="container">
        <header>
            <h1>MatEs</h1>
            <h3>Sistema de Matrícula Estudantil</h3>
        </header>
        <div class="avatar-section">
            <div class="avatar-placeholder">
                <label for="file-input" class="file-label">
                    <span>+</span>
                    <span>100x100</span>
                </label>
            </div>
            <input id="file-input" type="file" accept="image/*" style="display: none;">
        </div>
        <div class="buttons">
            <button onclick="matricula()">Matrícula</button>
            <button onclick="disciplinasMatriculadas()">Disciplinas Matriculadas</button>
            <button onclick="solicitarCurso()">Solicitar Curso</button>
            <button onclick = "desconectar()"style=" color: red;">Desconectar</button>
        </div>
    </div>

    <script src="scripts.js"></script>
</body>
</html>
