<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Diretor</title>
    <link rel="stylesheet" href="/assets/css/diretor_pedagogo.css">
</head>
<body>
    <div class="container">
        <h1>MatEs</h1>
        <h3>Sistema de Matrículas Escolares</h3>
        <button class="btn-default">Gerenciamento de Cursos</button>
        <button class="btn-default">Gerenciamento de Professores</button>
        <button class="btn-default">Gerenciamento de Alunos</button>
        <button class="btn-default">Cadastrar Aluno</button>
        <button class="btn-default">Horário</button>
        <button class="btn-logout">Desconectar</button>
    </div>
</body>
</html>
