<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Diretor</title>
    <link rel="stylesheet" href="/assets/css/diretor_pedagogo.css">
</head>
<body>
    <div class="container">
        <h1>MatEs</h1>
        <h3>Sistema de Matrículas Escolares</h3>
        <form action="process_buttons.php" method="post">
            <button type="submit" name="action" value="gerenciar_cursos" class="btn-default">Gerenciamento de Cursos</button>
        </form>
        <form action="process_buttons.php" method="post">
            <button type="submit" name="action" value="gerenciar_professores" class="btn-default">Gerenciamento de Professores</button>
        </form>
        <form action="process_buttons.php" method="post">
            <button type="submit" name="action" value="gerenciar_alunos" class="btn-default">Gerenciamento de Alunos</button>
        </form>
        <form action="cadastrar_aluno.php" method="post">
            <button type="submit" name="action" value="cadastrar_aluno.php" class="btn-default">Cadastrar Aluno</button>
        </form>
        <form action="process_buttons.php" method="post">
            <button type="submit" name="action" value="desconectar" class="btn-logout">Desconectar</button>
        </form>
    </div>
</body>
</html>
